//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderProducts = new HashSet<OrderProduct>();
            this.OrderProducts1 = new HashSet<OrderProduct>();
        }
    
        public int OrderID { get; set; }
        public string OrderNum { get; set; }
        public string BoxNum { get; set; }
        public string Hospital { get; set; }
        public string Doctor { get; set; }
        public string Patient { get; set; }
        public string OrderKind { get; set; }
        public Nullable<System.DateTime> SaveTime { get; set; }
        public Nullable<System.DateTime> AcceptDate { get; set; }
        public Nullable<System.DateTime> PlanDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public string Remark { get; set; }
        public Nullable<byte> IsFree { get; set; }
        public Nullable<byte> IsTry { get; set; }
        public Nullable<byte> IsTryFirst { get; set; }
        public Nullable<byte> IsRedo { get; set; }
        public string Products { get; set; }
        public string Pos1 { get; set; }
        public string Pos2 { get; set; }
        public string Pos3 { get; set; }
        public string Pos4 { get; set; }
        public string PosUp { get; set; }
        public string PosDown { get; set; }
        public Nullable<byte> OrderState { get; set; }
        public string TryOrRedo { get; set; }
        public string Salesman { get; set; }
        public Nullable<decimal> SumPrice { get; set; }
        public Nullable<decimal> RealPrice { get; set; }
        public Nullable<int> NetOrderId { get; set; }
        public string PatientID { get; set; }
        public Nullable<int> CureTimes { get; set; }
        public System.Guid Guid { get; set; }
        public int OrderType { get; set; }
        public Nullable<System.Guid> ForeignFactoryId { get; set; }
        public Nullable<bool> IsStageAdjustment { get; set; }
        public int DataType { get; set; }
        public Nullable<int> TeethModelType { get; set; }
        public string TeethModelTrackingNumber { get; set; }
        public string MedicalRecordNetIdentification { get; set; }
        public Nullable<System.DateTime> PatientBirthDay { get; set; }
        public string TeethModelID { get; set; }
        public string OrderNetIdentification { get; set; }
        public Nullable<int> OrderNetType { get; set; }
        public string Tag { get; set; }
        public Nullable<bool> IsReceiving { get; set; }
        public string ExpectedFactoryName { get; set; }
        public string Department { get; set; }
        public Nullable<int> ModelType { get; set; }
        public string ForeignFactoryName { get; set; }
        public Nullable<int> TryStage { get; set; }
        public Nullable<int> ReworkType { get; set; }
        public Nullable<int> OrderNetState { get; set; }
        public OrderProduct OrderProduct { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProducts1 { get; set; }
        public virtual Order Orders1 { get; set; }
        public virtual Order Order1 { get; set; }
    }
}
