//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewDLL
{
    using System;
    using System.Collections.Generic;
    
    public  class OrderProduct
    {
        public int OrderProductID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string Product { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> Num { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> SumPrice { get; set; }
        public string Pos1 { get; set; }
        public string Pos2 { get; set; }
        public string Pos3 { get; set; }
        public string Pos4 { get; set; }
        public string PosUp { get; set; }
        public string PosDown { get; set; }
        public Nullable<byte> IsRedo { get; set; }
        public string Remark { get; set; }
        public Nullable<byte> IsMaterial { get; set; }
        public Nullable<decimal> EffectiveCount { get; set; }
        public Nullable<byte> RowNum { get; set; }
        public Nullable<byte> RedoState { get; set; }
        public Nullable<byte> TryState { get; set; }
        public Nullable<int> FrontNum { get; set; }
        public Nullable<int> BackNum { get; set; }
        public Nullable<int> BasinNum { get; set; }
        public Nullable<int> LostNum { get; set; }
        public string MissingTP1 { get; set; }
        public string MissingTP2 { get; set; }
        public string MissingTP3 { get; set; }
        public string MissingTP4 { get; set; }
        public string Pontic { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Order Order1 { get; set; }
    }
}
